---
server:
  port: 8081
jwt:
  auth-header-name: Authorization
aws:
  access-key: ${AWS_ACCESS_KEY}
  access-secret: ${AWS_ACCESS_SECRET_KEY}
  region: ${AWS_REGION}
  jwkUrl: https://cognito-idp.eu-west-2.amazonaws.com/${userPoolId}/.well-known/jwks.json
  user-name-field: username
  groups-field: cognito:groups
  connection-timeout: 2000
  read-timeout: 2000
spring:
  security:
    oauth2:
      client:
        provider:
          cognito:
            issuerUri: https://cognito-idp.eu-west-2.amazonaws.com/${userPoolId}
            #user-name-attribute: cognito:username
  config:
    import: optional:aws-secretsmanager:secret/demo
